name: Build QMK firmware
on:
  push:
    branches:
      - main
      - master
      - 'develop**'
      - '.github/workflows/build-firmware'
jobs:
  Build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard: [ "mabroum/zazu:alaa", "mabroum/zazu:default", "mabroum/batreeqvcirque:default", "mabroum/batreeq:alaa", "mabroum/batreeqv2:alaa" ]
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository}}
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Build firmware
        shell: bash
        run: |
          make ${{ matrix.keyboard }}
      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: qmk_mabroum_${{ github.actor }}
          path: |
            *.hex
            *.bin
            *.uf2
